{% set name = "pycodestyle" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycodestyle-{{ version }}.tar.gz
  sha256: 442f950141b4f43df752dd303511ffded3a04c2b6fb7f65980574f0c31e6e79c

build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pycodestyle
  commands:
    - pip check
    - pycodestyle --help
  requires:
    - pip

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python style guide checker
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
