travis:
  secure:
    BINSTAR_TOKEN: j4Bn5iQww17ISwGFj3w7iENIm7xRLvziKsmoP948vaeURh0WVzeBW/+qVIQptxC2/aYXro+a7Toa5bxi4/xK9ojiluu168GQEj+gSqtQav2Qtu8oQ0EaF2kon5C9JaE3c5PRojVgR1v4MgTxoXaLEhnoFljD+dqC0xmFe1988eO9sVKgCNIWRuE1ny1xh7fJjWc6RrckzIX2bWzhrxoI9Ndn4f8JmOy6MKHSc1QlCIMPQRzaAoZ4Tpd40B5a+EfQA6Id8/yEHRljJDuHaC5Ik8AaybnnsAfZZ6hxJQFC1dW8dPvm9pnkZHSv123mqeGOvyiC1gPeXvQBmOLxY2J7nCggjHZuigyQNoDgqmPIYt3bEko2EHIZA0htKE1lzIz0ts3CPU1Sgke4rqz8M9qNdNxvGPoyMdhfHh/mP/6rf/3WONx6ctgcTuh4wFL55iY40dfTbVg7i3/6w68JmNfeO+TZwqZv+A5+Uwd/D3nqeUlym4fYGo9digret++vg9bjILRfogqv4Jm5u5tPkgFa0eh/SK6xawmiUwSksfCGJkr955CdKE8C6NI4BUNacNu51uKdAimHJhPBLjY40BXJ6+Fcy9YsNb2pB1vXTcOO6kz1k3+YyTzgdV+HDaNcg3tw/JgC+TxwDMo49ALtwQdyuEwcWpfU3EkvMbsru+j713M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
